version: "3"
        
services:  
    # nginx
    nginx:
        container_name: ${PROJECT_NAME}_nginx
        build: ./docker-assets/nginx
        volumes:
            - ./src:/src
            - ./docker-assets/nginx/conf.d:/etc/nginx/conf.d
        links:
            - php-fpm
        ports:
            - 8080:8080
        working_dir: /src
       
    # php
    php-fpm:
        container_name: ${PROJECT_NAME}_php-fpm
        build: ./docker-assets/php
        links:
            - pgsql
            - redis
        volumes:
            - ./src:/src
        working_dir: /src
        
    # database
    pgsql:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        container_name: ${PROJECT_NAME}_pgsql
        volumes: 
            - ./database:/var/lib/pgsql
        ports:
            - 5432:5432
        restart: always
        environment:
            POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
            POSTGRES_USER: ${PGSQL_USER}
            POSTGRES_DB: ${PGSQL_DATABASE}
    # adminer      
    adminer:
        container_name: ${PROJECT_NAME}_adminer
        image: adminer
        restart: always
        links:
            - pgsql
        ports:
            - 6080:8080
        environment:
            ADMINER_DESIGN: 'pepa-linha'
            ADMINER_DEFAULT_SERVER: mysql

    # redis
    redis:
        container_name: ${PROJECT_NAME}_redis
        image: redis:alpine
     
    # redis commander 
    redis-commander:
        container_name: ${PROJECT_NAME}_redis_commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        links:
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        ports:
            - 6081:8081
